            <!-- Example row of columns -->
            <div class="row">
                <div class="col-md-12">
                    <h2>A Empresa</h2>
                    <p><img src="img/livro.png" class="flutuar-img">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris nec risus libero. Donec semper tristique orci, vel rutrum tellus sagittis ac. Ut ac laoreet felis, sed varius neque. Donec iaculis a nisi id accumsan. Nunc ornare rhoncus lectus, sed luctus augue. Vivamus nibh libero, sagittis ac suscipit nec, iaculis in leo. Sed et feugiat metus. Nunc eleifend condimentum placerat. Mauris eget porttitor arcu.</p>
                    <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam sit amet elit dictum, suscipit nibh sit amet, imperdiet libero. Morbi ac lobortis mi, sed scelerisque urna. Vivamus rutrum enim nec nisl faucibus, vitae porttitor eros egestas. Fusce sit amet est ut enim imperdiet rutrum vitae nec leo. Sed non pretium felis. Mauris ut lacus eget nisi viverra blandit. Pellentesque laoreet dictum elementum. Nulla efficitur dui dolor. Vestibulum tempor magna vitae nulla mollis, eget sodales tellus sodales. Duis ut rutrum mauris.</p>
                    <p>Sed urna dolor, ornare at leo quis, lobortis convallis lacus. Sed sollicitudin ex nulla, tincidunt ultrices nibh scelerisque a. Praesent elementum leo at euismod dictum. Sed neque ante, iaculis ut euismod nec, fringilla et tortor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nibh libero, porttitor a odio ac, vulputate efficitur orci. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse vel nisi ac ex dictum faucibus. Mauris eget erat sem. In dignissim tortor vitae quam pharetra, ac venenatis enim eleifend.</p>
                    <p>Dignissim</p>
                </div>
            </div>